<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Laptop;

class LaptopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $laptops = [
            [
                'name' => 'MacBook Pro 14-inch M3 Pro',
                'description' => 'Powerful laptop with Apple M3 Pro chip, perfect for professionals and creatives.',
                'price' => 1999.00,
                'brand' => 'Apple',
                'processor' => 'Apple M3 Pro',
                'ram' => '18GB',
                'storage' => '512GB SSD',
                'display' => '14-inch Retina',
                'graphics' => 'Integrated M3 Pro',
                'operating_system' => 'macOS Sonoma',
                'color' => 'Space Gray',
                'stock_quantity' => 15,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Dell XPS 13 Plus',
                'description' => 'Ultra-thin laptop with stunning display and premium build quality.',
                'price' => 1499.00,
                'brand' => 'Dell',
                'processor' => 'Intel Core i7-1360P',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'display' => '13.4-inch 4K OLED',
                'graphics' => 'Intel Iris Xe',
                'operating_system' => 'Windows 11',
                'color' => 'Platinum',
                'stock_quantity' => 12,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'HP Spectre x360 14',
                'description' => 'Convertible 2-in-1 laptop with premium design and excellent performance.',
                'price' => 1299.00,
                'brand' => 'HP',
                'processor' => 'Intel Core i7-1355U',
                'ram' => '16GB',
                'storage' => '1TB SSD',
                'display' => '14-inch 2.8K OLED',
                'graphics' => 'Intel Iris Xe',
                'operating_system' => 'Windows 11',
                'color' => 'Nightfall Black',
                'stock_quantity' => 8,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Lenovo ThinkPad X1 Carbon',
                'description' => 'Business laptop with legendary durability and enterprise features.',
                'price' => 1699.00,
                'brand' => 'Lenovo',
                'processor' => 'Intel Core i7-1355U',
                'ram' => '32GB',
                'storage' => '1TB SSD',
                'display' => '14-inch 2.8K OLED',
                'graphics' => 'Intel Iris Xe',
                'operating_system' => 'Windows 11 Pro',
                'color' => 'Black',
                'stock_quantity' => 20,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'ASUS ROG Zephyrus G14',
                'description' => 'Gaming laptop with AMD Ryzen processor and RTX graphics.',
                'price' => 1599.00,
                'brand' => 'ASUS',
                'processor' => 'AMD Ryzen 9 7940HS',
                'ram' => '32GB',
                'storage' => '1TB SSD',
                'display' => '14-inch QHD 165Hz',
                'graphics' => 'NVIDIA RTX 4060',
                'operating_system' => 'Windows 11',
                'color' => 'Moonlight White',
                'stock_quantity' => 10,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'MSI GS66 Stealth',
                'description' => 'Slim gaming laptop with powerful performance and sleek design.',
                'price' => 1899.00,
                'brand' => 'MSI',
                'processor' => 'Intel Core i7-13700H',
                'ram' => '32GB',
                'storage' => '2TB SSD',
                'display' => '15.6-inch QHD 240Hz',
                'graphics' => 'NVIDIA RTX 4070',
                'operating_system' => 'Windows 11',
                'color' => 'Black',
                'stock_quantity' => 6,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Razer Blade 15',
                'description' => 'Premium gaming laptop with aluminum chassis and RGB lighting.',
                'price' => 2499.00,
                'brand' => 'Razer',
                'processor' => 'Intel Core i9-13900H',
                'ram' => '32GB',
                'storage' => '2TB SSD',
                'display' => '15.6-inch QHD 240Hz',
                'graphics' => 'NVIDIA RTX 4080',
                'operating_system' => 'Windows 11',
                'color' => 'Black',
                'stock_quantity' => 4,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Acer Swift 3',
                'description' => 'Affordable ultrabook with great battery life and portability.',
                'price' => 699.00,
                'brand' => 'Acer',
                'processor' => 'AMD Ryzen 7 7735U',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'display' => '14-inch FHD',
                'graphics' => 'AMD Radeon Graphics',
                'operating_system' => 'Windows 11',
                'color' => 'Silver',
                'stock_quantity' => 25,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Microsoft Surface Laptop 5',
                'description' => 'Premium Windows laptop with excellent build quality and display.',
                'price' => 1199.00,
                'brand' => 'Microsoft',
                'processor' => 'Intel Core i7-1255U',
                'ram' => '16GB',
                'storage' => '512GB SSD',
                'display' => '13.5-inch PixelSense',
                'graphics' => 'Intel Iris Xe',
                'operating_system' => 'Windows 11',
                'color' => 'Platinum',
                'stock_quantity' => 18,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Samsung Galaxy Book3 Pro',
                'description' => 'Samsung premium laptop with AMOLED display and sleek design.',
                'price' => 1399.00,
                'brand' => 'Samsung',
                'processor' => 'Intel Core i7-1360P',
                'ram' => '16GB',
                'storage' => '1TB SSD',
                'display' => '14-inch AMOLED',
                'graphics' => 'Intel Iris Xe',
                'operating_system' => 'Windows 11',
                'color' => 'Graphite',
                'stock_quantity' => 12,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'MacBook Air 13-inch M2',
                'description' => 'Ultra-portable laptop with Apple M2 chip and all-day battery life.',
                'price' => 1199.00,
                'brand' => 'Apple',
                'processor' => 'Apple M2',
                'ram' => '8GB',
                'storage' => '256GB SSD',
                'display' => '13.6-inch Liquid Retina',
                'graphics' => 'Integrated M2',
                'operating_system' => 'macOS Ventura',
                'color' => 'Midnight',
                'stock_quantity' => 30,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Dell Inspiron 15 3000',
                'description' => 'Budget-friendly laptop perfect for everyday computing tasks.',
                'price' => 449.00,
                'brand' => 'Dell',
                'processor' => 'Intel Core i5-1235U',
                'ram' => '8GB',
                'storage' => '256GB SSD',
                'display' => '15.6-inch FHD',
                'graphics' => 'Intel UHD Graphics',
                'operating_system' => 'Windows 11',
                'color' => 'Black',
                'stock_quantity' => 35,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($laptops as $laptop) {
            Laptop::create($laptop);
        }
    }
}
